### ISSUE TITLE
Incompatible with other mods that provide Aegis 3.0.0 like Playtime Tracker

### ISSUE THREAD

**Issue by JoeJoeTV** [The-Tiny-Taters/Better-Op#1]
When installed together with other mods that provide version 3.0.0 of [Aegis](https://github.com/P03W/Aegis), the server crashes with the following error and no crash report is generated:

```Exception in thread "main" [19:24:09] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[19:24:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
[19:24:09] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[19:24:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
[19:24:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
[19:24:09] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[19:24:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
[19:24:09] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
[19:24:09] [main/INFO]: [STDERR]:       ... 1 more
[19:24:10] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
[19:24:10] [main/INFO]: [STDERR]:       ... 2 more
[19:24:10] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
[19:24:10] [main/INFO]: [STDERR]:       ... 7 more
[19:24:10] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[19:24:10] [main/INFO]: [STDERR]:       ... 9 more
[19:24:10] [main/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodError: 'void com.github.p03w.aegis.AegisCommandBuilder.setChainHasExecute(boolean)'
[19:24:10] [main/INFO]: [STDERR]:       at the_tiny_taters.better_op.command.OpCommand$register$1.invoke(OpCommand.java:82)
[19:24:10] [main/INFO]: [STDERR]:       at the_tiny_taters.better_op.command.OpCommand$register$1.invoke(OpCommand.java:16)
[19:24:10] [main/INFO]: [STDERR]:       at com.github.p03w.aegis.AegisCommandBuilder.<init>(AegisCommandBuilder.java:36)
[19:24:10] [main/INFO]: [STDERR]:       at com.github.p03w.aegis.AegisKt.aegisCommand(AegisKt.java:520)
[19:24:10] [main/INFO]: [STDERR]:       at the_tiny_taters.better_op.command.OpCommand.register(OpCommand.java:18)
[19:24:10] [main/INFO]: [STDERR]:       at the_tiny_taters.better_op.Common$onInitialize$1.register(Common.java:13)
[19:24:10] [main/INFO]: [STDERR]:       at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41)
[19:24:10] [main/INFO]: [STDERR]:       at net.minecraft.class_2170.handler$zdm000$fabric_addCommands(class_2170.java:547)
[19:24:10] [main/INFO]: [STDERR]:       at net.minecraft.class_2170.<init>(class_2170.java:233)
[19:24:10] [main/INFO]: [STDERR]:       at net.minecraft.class_5350.<init>(class_5350.java:34)
[19:24:10] [main/INFO]: [STDERR]:       at net.minecraft.class_5350.method_29466(class_5350.java:78)
[19:24:10] [main/INFO]: [STDERR]:       at net.minecraft.server.Main.main(Main.java:134)
[19:24:10] [main/INFO]: [STDERR]:       ... 14 more
```

Specs:
- Minecraft 1.16.5
- Java 16
- Fabric Loader 0.11.6
- BetterOP 1.0.3

I found a notice on the [Release of Aegis 3.0.0 on Github](https://github.com/P03W/Aegis/releases/tag/3.0.0), that mentions, that this version is not binary compatible to previous versions and mods need to be recompiled, which is likely the problem.

**Comment by spaceclouds42** [comment]
I'll update this as soon as I can, thanks for opening the issue.
